name: Gold Price Bot

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 升级到 v4，支持更高版本的 Node.js
      - uses: actions/checkout@v4 

      # 2. 升级到 v4，并将 node-version 改为 24
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' 

      - name: Install deps
        run: npm install

      - name: Run
        env:
          ALI_APP_CODE: ${{ secrets.ALI_APP_CODE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        run: node monitor.js
